spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/oauth2
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-name: naver
#            client-id:
#            client-secret:
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name,email,nickname,gender,age,mobile
#
#          google:
#            client-name: google
#            client-id:
#            client-secret:
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            scope: profile,email
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#

